### ISSUE TITLE
Failure to return any results for some coordinates

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/nuts_finder#3]
With some coordinates, the finder returns an empty list. 

Eg

`nf = NutsFinder()`
`nf.find(lat=51.50148,lon=0.00527)`
`[]`

I have found that it fails with the following coordinates:

51.50148, 0.00527
51.5074, 0.0648
50.79527, -1.09357
50.79527, -1.09357

**Comment by jaklinger** [comment]
Thanks @Juan-Mateos - I've just added a note to the docs:

https://github.com/nestauk/nuts_finder#points-near-rivers-and-coastlines

which explains that near rivers and coastlines you might expect to have missing points. The solution is to use `scale=1`. The reason for not doing this by default is for speed, as for processing many thousands (or more) points this will become very slow. Your choices are either:

1) Deal with `scale=1` being slow
2) Do a coarser search with the default `NutsFinder()`, and then pick up missing values using `NutsFinder(scale=1)`
